# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010iclg225-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gustav/ArquiGustavoWolfmann/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/gustav/ArquiGustavoWolfmann/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/gustav/ArquiGustavoWolfmann/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/EX.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/ID.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/IF.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/MEM.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/WB.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/adder.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/alu.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/alu_control.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/control_id.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/control_pc.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/cortocircuito.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/data_mem.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/hazard.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/prog_mem.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/register_id.v
  /home/gustav/ArquiGustavoWolfmann/project_1/project_1.srcs/sources_1/new/top_pipe.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_pipe -part xc7z010iclg225-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_pipe.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_pipe_utilization_synth.rpt -pb top_pipe_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
